# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-13 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_fantasyleaderboard_fantasypicks_fantasypointstable'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsSpread',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('surfer_name', models.TextField(blank=True, null=True)),
                ('event_id', models.IntegerField(blank=True, null=True)),
                ('tourpoints', models.IntegerField(blank=True, null=True)),
                ('tourfantasypoints', models.FloatField(blank=True, null=True)),
                ('lasteventfantasypoints', models.FloatField(blank=True, null=True)),
                ('tourmaxheatscore', models.FloatField(blank=True, null=True)),
                ('lasteventmaxheatscore', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pointsspread',
                'managed': False,
            },
        ),
    ]
