# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_pointsspread'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pointsspread',
            table='PointsSpread',
        ),
    ]
